ALTER TABLE dim_projeto ADD COLUMN IF NOT EXISTS incluir_cortesias BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE evento_grupos ADD COLUMN IF NOT EXISTS incluir_cortesias BOOLEAN NOT NULL DEFAULT FALSE;
